export const USER_SIGN_REQUEST = 'USER_SIGN_REQUEST';
export const USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS';
export const USER_SIGN_FAIL = 'USER_SIGN_FAIL';

export const USER_SIGN_UP_REQUEST = 'USER_SIGN_UP_REQUEST';
export const USER_SIGN_UP_SUCCESS = 'USER_SIGN_UP_SUCCESS';
export const USER_SIGN_UP_FAIL = 'USER_SIGN_UP_FAIL';

export const USER_SIGN_OUT = 'USER_SIGN_OUT';